global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090 # 本地prometheus
  - job_name: ws-cluster
    honor_timestamps: true
    scrape_interval: 3s
    scrape_timeout: 2s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:9091 # 宿主机golang
  - job_name: wikitrade
    honor_timestamps: true
    scrape_interval: 3s
    scrape_timeout: 2s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:9093 # 服务器golang
