{
 "title": "websocket集群",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ws连接数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ws_connection{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "队列每秒平均消息处理数量",
   "type": "timeseries",
   "description": "队列每秒平均消息处理数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(queue_handle_total{job=\"ws-cluster\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5分钟消息处理时间p999",
   "type": "timeseries",
   "description": "计算过去 5分钟内 第 999 个百分位数",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, rate(queue_handle_duration_bucket[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}