# et 代表可以通过环境变量和命令参数覆盖的配置项,命令行参数优先级大于环境变量
env: local #et(WS_ENV,env)  local, dev, prod
node: 100 #et(WS_NODE,node) 节点编号

ws_server:
  port: 8084
http_server:
  port: 8085

log:
  path: /Users/mtgnorton/Coding/go/src/github.com/mtgnorton/ws-cluster/logs
  print: true # 是否打印日志
  level: debug # 日志级别 debug, info, warn, error,dpanic, panic, fatal
  max_age: 7 # 日志保存天数
  max_size: 100 # 单个日志文件大小，单位MB
  max_backups: 10 # 日志文件最大备份数
  compress: true # 是否压缩日志
redis:
  addr: localhost:6379
  port: 6379
  user: ""
  password: ""
  db: 3
redis_queue:
  addr: localhost:6379
  port:
  user: ""
  password: ""
  db: 4
sentry: # 如果dsn为空，则不启用sentry
  #dsn: ""
  dsn: "https://51da076279386f0174c2d3237aeb657e@o4506597786517504.ingest.sentry.io/4506597788614656"
  traces_sample_rate: 1.0
#通过docker-compose启动， prometheus的web访问地址为 http://localhost:9092，grafana的web访问地址为 http://localhost:3000,user: admin,password: grafana
prometheus:
  enable: true
  path: /metrics
  addr: :9091
